version: '3.8'

services:
  frontend:
    build:
      context: ./web/ragbot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL_ID=${GEMINI_MODEL_ID}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      # Add any other volumes your backend needs
